In [1]:
import pandas as pd
import numpy as np
import os

In [12]:
print(os.getcwd())

C:\Users\heche\00000-project-2026\003_ecommerce_business_analysis\notebooks

In [13]:
print(os.listdir())

['.ipynb_checkpoints', '01_data_understanding.ipynb']

In [8]:
customers = pd.read_csv("../data/raw/customers.csv")
orders = pd.read_csv("../data/raw/orders.csv")
orders_items = pd.read_csv("../data/raw/orders_items.csv")
products = pd.read_csv("../data/raw/products.csv")
products_skus = pd.read_csv("../data/raw/products_skus.csv")
traffic = pd.read_csv("../data/raw/traffic.csv")
transactions = pd.read_csv("../data/raw/transactions.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [9]:
print("customers:", customers.shape)
print("orders:", orders.shape)
print("orders_items:", orders_items.shape)
print("products:", products.shape)
print("products_skus:", products_skus.shape)
print("traffic:", traffic.shape)
print("transactions:", transactions.shape)

customers: (44661, 3)
orders: (21358, 13)
orders_items: (36826, 10)
products: (247, 5)
products_skus: (1356, 6)
traffic: (579, 8)
transactions: (27563, 8)

In [10]:
customers.head()

           id       full_name  created_at
0  8652230815             NaN  2016-08-16
1  8686141151    Warren Perez  2016-08-22
2  8686909727  Micheal Robles  2016-08-22
3  8686915935   Michael Ellis  2016-08-22
4  8686918303  Robert Stewart  2016-08-22

In [18]:
#建立 dataset
datasets = {
    "customers": customers,
    "orders": orders,
    "orders_items": orders_items,
    "products": products,
    "products_skus": products_skus,
    "traffic": traffic,
    "transactions": transactions
}

print("Dataset dictionary created successfully!")

Dataset dictionary created successfully!

In [20]:
#一次查看所有表的前5行
from IPython.display import display

for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    display(df.head())

======================================================================
CUSTOMERS

           id       full_name  created_at
0  8652230815             NaN  2016-08-16
1  8686141151    Warren Perez  2016-08-22
2  8686909727  Micheal Robles  2016-08-22
3  8686915935   Michael Ellis  2016-08-22
4  8686918303  Robert Stewart  2016-08-22

======================================================================
ORDERS

,id,created_at,closed_at,cancelled_at,customer_id,financial_status,fulfillment_status,processed_at,total_price,shipping_rate,subtotal_price,total_discounts,total_line_items_price
0,7675398239,2016-08-21,2016-08-25,2016-08-22,8683754719,voided,NaN,2016-08-21,44.57,6.33,35.0,0.0,35.0
1,7676331935,2016-08-22,2016-08-22,NaN,8686224991,refunded,NaN,2016-08-22,124.55,0.00,114.0,0.0,114.0
2,7676363167,2016-08-22,NaN,2016-08-22,8686224991,voided,NaN,2016-08-22,97.68,7.00,83.0,0.0,83.0
3,7676539359,2016-08-22,2016-08-22,NaN,8686915935,paid,fulfilled,2016-08-22,131.10,0.00,120.0,0.0,120.0
4,7676549855,2016-08-22,2016-08-22,NaN,8686924319,paid,fulfilled,2016-08-22,91.12,7.00,77.0,0.0,77.0

======================================================================
ORDERS_ITEMS

,id,order_id,product_id,product_style,variant_id,sku,product_title,fulfillment_status,price,quantity
0,13325125855,7675398239,1.292763e+10,2c259a42d38f5f097274beff811168e2,50547057311,000d96b3b77b33af530eec77689bd210,5cfd6c4e00b25e6dec5538928206b7b8,NaN,35.0,1
1,13327045983,7676331935,1.292763e+10,dd804c4025d230467823200aa82e9219,50547118303,e26c77e84b91c9939c23c3e3ef66475a,0e6e45ad42707e9732119f4b98aec7ce,NaN,79.0,1
2,13327109727,7676363167,1.292806e+10,f4e2e3c5433e4120889e2a7e0e0180a8,50553858975,0be0c8bf78ecf36416a40c9012acd19e,bede8c8f4e3c9c9d9a061d9a8d086cdc,NaN,58.0,1
3,13327495903,7676539359,1.292763e+10,08ba660ec5643520a73108bef6f3ddd6,50547001887,0503dec809a8a2600d9acc5249900ecb,27d598cb953eff3667f7d051fe795284,fulfilled,25.0,1
4,13327518751,7676549855,1.292769e+10,68ac90e5df73ae9b662174b21dc1586f,50548035807,38de0d087208588510907b5c2d149e4b,07dd8ba2ccadf3f3766750f10f6d05b5,fulfilled,25.0,1

======================================================================
PRODUCTS

,id,title,product_type,created_at,published_at
0,12927633311,6d1eeb39ae340f8d01d93779f80595ed,Dress,2016-08-18,2016-08-18
1,12927632095,0e6e45ad42707e9732119f4b98aec7ce,Bomber,2016-08-18,2016-08-18
2,12927625695,27d598cb953eff3667f7d051fe795284,Shirts,2016-08-18,2018-02-05
3,12928059103,fb337868ffefe5e008e8dc6d6a4f283a,Blazer,2016-08-18,2016-08-18
4,12927632799,d57bc87aca919b4758da6974cdf607fa,Hooide,2016-08-18,NaN

======================================================================
PRODUCTS_SKUS

,id,product_id,product_style,sku,created_at,price
0,50547147871,12927633311,d510a563d66df17daf05e72a6af123b7,0ecbe4277237cb1207b31815166d37b9,2016-08-18,29.0
1,50547117727,12927632095,dd804c4025d230467823200aa82e9219,f8e9bf1495c45676e8822e7ad4c97a93,2016-08-18,39.5
2,4886503364093,375446050301,8f61ed9720d09c9303fbc0b3184d478d,ccf2a80ad99d9dc449fbd5a904210d2c,2016-11-14,24.0
3,50547000415,12927625695,08ba660ec5643520a73108bef6f3ddd6,db1ea83c6299a2df5e39e420223fbd81,2016-08-18,25.0
4,50547135135,12927632799,6056dc7fb0e6987bfb6d08a8a707446f,c4f9cdb1df7a9add57df53e34290cbeb,2016-08-18,31.5

======================================================================
TRAFFIC

,index,date_day,page_views,sessions,product_detail_views,product_checkouts,product_adds_to_carts,avg_session_in_s
0,0,2016-08-17,204,6,0,0,0,2374.166667
1,1,2016-08-18,661,27,0,0,0,1632.111111
2,2,2016-08-19,241,12,0,0,0,1891.250000
3,3,2016-08-20,534,23,0,0,0,1557.956522
4,4,2016-08-21,10276,4946,0,0,0,73.470481

======================================================================
TRANSACTIONS

,order_id,id,parent_id,amount,error_code,kind,status,created_at
0,7675398239,8330669343,NaN,44.57,NaN,authorization,success,2016-08-21
1,7675398239,8331258783,8.330669e+09,0.00,NaN,void,success,2016-08-21
2,7676331935,8331688479,NaN,124.55,NaN,authorization,success,2016-08-21
3,7676363167,8331722975,NaN,97.68,NaN,authorization,success,2016-08-21
4,7676539359,8331919391,NaN,131.10,NaN,authorization,success,2016-08-21

In [21]:
# 查看所有列名
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    print(df.columns.tolist())

======================================================================
CUSTOMERS
['id', 'full_name', 'created_at']
======================================================================
ORDERS
['id', 'created_at', 'closed_at', 'cancelled_at', 'customer_id', 'financial_status', 'fulfillment_status', 'processed_at', 'total_price', 'shipping_rate', 'subtotal_price', 'total_discounts', 'total_line_items_price']
======================================================================
ORDERS_ITEMS
['id', 'order_id', 'product_id', 'product_style', 'variant_id', 'sku', 'product_title', 'fulfillment_status', 'price', 'quantity']
======================================================================
PRODUCTS
['id', 'title', 'product_type', 'created_at', 'published_at']
======================================================================
PRODUCTS_SKUS
['id', 'product_id', 'product_style', 'sku', 'created_at', 'price']
======================================================================
TRAFFIC
['index', 'date_day', 'page_views', 'sessions', 'product_detail_views', 'product_checkouts', 'product_adds_to_carts', 'avg_session_in_s']
======================================================================
TRANSACTIONS
['order_id', 'id', 'parent_id', 'amount', 'error_code', 'kind', 'status', 'created_at']

In [22]:
# 查看数据类型
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    print(df.dtypes)

======================================================================
CUSTOMERS
id             int64
full_name     object
created_at    object
dtype: object
======================================================================
ORDERS
id                          int64
created_at                 object
closed_at                  object
cancelled_at               object
customer_id                 int64
financial_status           object
fulfillment_status         object
processed_at               object
total_price               float64
shipping_rate             float64
subtotal_price            float64
total_discounts           float64
total_line_items_price    float64
dtype: object
======================================================================
ORDERS_ITEMS
id                      int64
order_id                int64
product_id            float64
product_style          object
variant_id              int64
sku                    object
product_title          object
fulfillment_status     object
price                 float64
quantity                int64
dtype: object
======================================================================
PRODUCTS
id               int64
title           object
product_type    object
created_at      object
published_at    object
dtype: object
======================================================================
PRODUCTS_SKUS
id                 int64
product_id         int64
product_style     object
sku               object
created_at        object
price            float64
dtype: object
======================================================================
TRAFFIC
index                      int64
date_day                  object
page_views                 int64
sessions                   int64
product_detail_views       int64
product_checkouts          int64
product_adds_to_carts      int64
avg_session_in_s         float64
dtype: object
======================================================================
TRANSACTIONS
order_id        int64
id              int64
parent_id     float64
amount        float64
error_code     object
kind           object
status         object
created_at     object
dtype: object

In [23]:
#检查缺失值
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    print(df.isnull().sum())

======================================================================
CUSTOMERS
id                0
full_name     10962
created_at        0
dtype: int64
======================================================================
ORDERS
id                            0
created_at                    0
closed_at                  1163
cancelled_at              20948
customer_id                   0
financial_status              0
fulfillment_status          678
processed_at                  0
total_price                   0
shipping_rate                 0
subtotal_price                0
total_discounts               0
total_line_items_price        0
dtype: int64
======================================================================
ORDERS_ITEMS
id                       0
order_id                 0
product_id              24
product_style            0
variant_id               0
sku                      0
product_title            0
fulfillment_status    1569
price                    0
quantity                 0
dtype: int64
======================================================================
PRODUCTS
id               0
title            0
product_type     5
created_at       0
published_at    24
dtype: int64
======================================================================
PRODUCTS_SKUS
id               0
product_id       0
product_style    0
sku              0
created_at       0
price            0
dtype: int64
======================================================================
TRAFFIC
index                    0
date_day                 0
page_views               0
sessions                 0
product_detail_views     0
product_checkouts        0
product_adds_to_carts    0
avg_session_in_s         0
dtype: int64
======================================================================
TRANSACTIONS
order_id          0
id                0
parent_id     22686
amount            0
error_code    25920
kind              0
status            0
created_at        0
dtype: int64

In [24]:
# 检查完整的重复行
for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()
    print(f"{name}: {duplicate_count} duplicated rows")

customers: 0 duplicated rows
orders: 0 duplicated rows
orders_items: 0 duplicated rows
products: 0 duplicated rows
products_skus: 0 duplicated rows
traffic: 0 duplicated rows
transactions: 0 duplicated rows

In [27]:
#检查主键是否重复
print("customers id duplicates:",
      customers["id"].duplicated().sum())

print("orders id duplicates:",
      orders["id"].duplicated().sum())

print("orders_items id duplicates:",
      orders_items["id"].duplicated().sum())

print("products id duplicates:",
      products["id"].duplicated().sum())

print("products_skus id duplicates:",
      products_skus["id"].duplicated().sum())

print("transactions id duplicates:",
      transactions["id"].duplicated().sum())
# 检查 index 是否重复
print("traffic index duplicates:",
      traffic["index"].duplicated().sum())

# 检查 date_day 是否重复
print("traffic date duplicates:",
      traffic["date_day"].duplicated().sum())

#下面的output说明这说明目前每张表的主键或唯一标识都很干净

customers id duplicates: 0
orders id duplicates: 0
orders_items id duplicates: 0
products id duplicates: 0
products_skus id duplicates: 0
transactions id duplicates: 0
traffic index duplicates: 0
traffic date duplicates: 0

In [47]:
# ===================================================================
# 订单中的 customer_id 是否都能在 customers 表中找到
missing_customer_ids = (
    ~orders["customer_id"].isin(customers["id"])
).sum()

print(
    "Orders with customer_id not found in customers:",
    missing_customer_ids
)
# orders_items 中的 order_id 是否都能在 orders 表中找到
missing_order_ids = (
    ~orders_items["order_id"].isin(orders["id"])
).sum()

print(
    "Order items with order_id not found in orders:",
    missing_order_ids
)
# transactions 中的 order_id 是否都能在 orders 表中找到
missing_transaction_order_ids = (
    ~transactions["order_id"].isin(orders["id"])
).sum()

print(
    "Transactions with order_id not found in orders:",
    missing_transaction_order_ids
)

Orders with customer_id not found in customers: 0
Order items with order_id not found in orders: 4
Transactions with order_id not found in orders: 0

In [32]:
# 找出无法匹配到 orders 表的订单商品记录
orphan_order_items = orders_items[
    ~orders_items["order_id"].isin(orders["id"])
]

orphan_order_items

,id,order_id,product_id,product_style,variant_id,sku,product_title,fulfillment_status,price,quantity
8687,380774979069,197355247101,3.754461e+11,c181d5d7597a1e506e723de23374cf04,4886503790077,f734ec58f86852632269df64ffd38d59,640a203c4db6ca5aa608ad5979278b0f,fulfilled,45.0,1
21844,1418643346941,559628752381,7.192442e+11,46ed7edb963045b881e39089efcd3248,8058838455805,984c865a721cffde355bac24f02be7c0,2f213854913be17a393421ccf9d391db,NaN,42.0,1
25869,1418643379709,559628752381,7.192428e+11,29c422957ef3d1848861d4678350a634,8058831508989,60e03335376388bd4eb35333b0a7e323,2db8af033406b6667239b4f8beea9b46,NaN,32.0,1
27664,1418643412477,559628752381,5.212644e+11,1e6c4b8df5457fdb678f9430ac231946,6942278129149,35246df4e017e973b2a8d92bd344445c,9cd2bdb6922a4edcdeb20212b436fb0a,fulfilled,25.0,1

In [33]:
print("Number of orphan order items:", len(orphan_order_items))

Number of orphan order items: 4

In [35]:
orphan_order_items["order_id"].unique()
#这步的目的
#是4条记录对应4个不同订单
#还是一个订单里有4个商品

array([197355247101, 559628752381], dtype=int64)

In [36]:
# 查看每个孤立订单包含多少条商品记录
orphan_order_items.groupby("order_id").size()

order_id
197355247101    1
559628752381    3
dtype: int64

In [38]:
#只查看有用列
orphan_order_items[
    [
        "id",
        "order_id",
        "product_id",
        "product_title",
        "price",
        "quantity"
    ]
]

,id,order_id,product_id,product_title,price,quantity
8687,380774979069,197355247101,3.754461e+11,640a203c4db6ca5aa608ad5979278b0f,45.0,1
21844,1418643346941,559628752381,7.192442e+11,2f213854913be17a393421ccf9d391db,42.0,1
25869,1418643379709,559628752381,7.192428e+11,2db8af033406b6667239b4f8beea9b46,32.0,1
27664,1418643412477,559628752381,5.212644e+11,9cd2bdb6922a4edcdeb20212b436fb0a,25.0,1

In [44]:
#再计算这4条记录的商品金额
orphan_order_items = orphan_order_items.copy()

orphan_order_items["item_revenue"] = (
    orphan_order_items["price"]
    * orphan_order_items["quantity"]
)

orphan_order_items[
    [
        "order_id",
        "product_title",
        "price",
        "quantity",
        "item_revenue"
    ]
]

,order_id,product_title,price,quantity,item_revenue
8687,197355247101,640a203c4db6ca5aa608ad5979278b0f,45.0,1,45.0
21844,559628752381,2f213854913be17a393421ccf9d391db,42.0,1,42.0
25869,559628752381,2db8af033406b6667239b4f8beea9b46,32.0,1,32.0
27664,559628752381,9cd2bdb6922a4edcdeb20212b436fb0a,25.0,1,25.0

In [46]:
#然后算总金额
print(
    "Total revenue of orphan order items:",
    orphan_order_items["item_revenue"].sum()
)

Total revenue of orphan order items: 144.0

### Orphan Order Items Finding
订单号	商品条数	商品金额
197355247101	1	45
559628752381	3	99
合计	4	144

Four order-item records could not be matched to the orders dataset.

- These records belong to two missing orders.
- Their combined item value is 144.
- Because the related order status, customer, payment, and cancellation information cannot be verified, these records will be excluded from order-based sales analysis.

In [49]:
# =================================================================
# 检查非空 product_id 是否都能在 products 表中找到
valid_product_ids = orders_items["product_id"].dropna()

missing_product_ids = (
    ~valid_product_ids.isin(products["id"])
).sum()

print(
    "Order items with product_id not found in products:",
    missing_product_ids
)

Order items with product_id not found in products: 0

In [51]:
# =================================================================
# 检查 variant_id 是否都能在 products_skus 表中找到
missing_variant_ids = (
    ~orders_items["variant_id"].isin(products_skus["id"])
).sum()

print(
    "Order items with variant_id not found in products_skus:",
    missing_variant_ids
)

Order items with variant_id not found in products_skus: 1360

In [53]:
# =================================================================
# 检查 sku 是否都能在 products_skus 表中找到
missing_skus = (
    ~orders_items["sku"].isin(products_skus["sku"])
).sum()

print(
    "Order items with sku not found in products_skus:",
    missing_skus
)

Order items with sku not found in products_skus: 354

In [54]:
#先确认variant_id和sku本身有没有空值：
print(
    "Missing variant_id:",
    orders_items["variant_id"].isna().sum()
)

print(
    "Missing sku:",
    orders_items["sku"].isna().sum()
)

Missing variant_id: 0
Missing sku: 0

In [55]:
test_variant_id = orders_items.loc[0, "variant_id"]

print("Variant ID from order item:")
print(test_variant_id)

products_skus[
    products_skus["id"] == test_variant_id
]

Variant ID from order item:
50547057311

,id,product_id,product_style,sku,created_at,price
1135,50547057311,12927629215,2c259a42d38f5f097274beff811168e2,000d96b3b77b33af530eec77689bd210,2016-08-18,35.0

### Variant ID Relationship

The `variant_id` field in `orders_items` corresponds to the `id` field in `products_skus`.

A sample lookup confirmed that the same variant ID exists in both tables and is associated with the same SKU and product style.

Therefore, the intended relationship is:

`orders_items.variant_id` → `products_skus.id`

In [56]:
# 匹配不上的订单商品记录数量
unmatched_variant_row_count = (
    ~orders_items["variant_id"].isin(products_skus["id"])
).sum()

# 匹配不上的不同 variant_id 数量
unmatched_variant_id_count = (
    orders_items.loc[
        ~orders_items["variant_id"].isin(products_skus["id"]),
        "variant_id"
    ]
    .nunique()
)

print(
    "Order-item rows with variant_id not found:",
    unmatched_variant_row_count
)

print(
    "Unique variant IDs not found:",
    unmatched_variant_id_count
)

Order-item rows with variant_id not found: 1360
Unique variant IDs not found: 41

In [57]:
# 匹配不上的订单商品记录数量
unmatched_sku_row_count = (
    ~orders_items["sku"].isin(products_skus["sku"])
).sum()

# 匹配不上的不同 SKU 数量
unmatched_sku_count = (
    orders_items.loc[
        ~orders_items["sku"].isin(products_skus["sku"]),
        "sku"
    ]
    .nunique()
)

print(
    "Order-item rows with SKU not found:",
    unmatched_sku_row_count
)

print(
    "Unique SKUs not found:",
    unmatched_sku_count
)

Order-item rows with SKU not found: 354
Unique SKUs not found: 29

In [58]:
#====================================================================
# 查看订单的财务状态
orders["financial_status"].value_counts(dropna=False)

financial_status
paid                  17846
partially_refunded     2409
refunded               1093
pending                   6
voided                    4
Name: count, dtype: int64

In [59]:
# 查看订单配送/履约状态
orders["fulfillment_status"].value_counts(dropna=False)

fulfillment_status
fulfilled    20369
NaN            678
partial        309
restocked        2
Name: count, dtype: int64

In [60]:
# cancelled_at 不为空，说明订单被取消
cancelled_order_count = orders["cancelled_at"].notna().sum()

print("Cancelled orders:", cancelled_order_count)

Cancelled orders: 410

In [61]:
#再计算取消率
cancelled_order_rate = (
    cancelled_order_count / len(orders) * 100
)

print(f"Cancelled order rate: {cancelled_order_rate:.2f}%")

Cancelled order rate: 1.92%

In [62]:
# 查看交易种类
transactions["kind"].value_counts(dropna=False)

kind
sale             21540
refund            3812
authorization     1156
capture           1051
void                 4
Name: count, dtype: int64

In [63]:
# 查看交易结果
transactions["status"].value_counts(dropna=False)

status
success    25703
failure     1840
pending       18
error          2
Name: count, dtype: int64

In [67]:
#交易成功率计算
successful_transactions = (
    transactions["status"] == "success"
).sum()

transaction_success_rate = (
    successful_transactions / len(transactions) * 100
)

print("Successful transactions:", successful_transactions)
print(f"Transaction success rate: {transaction_success_rate:.2f}%")

Successful transactions: 25703
Transaction success rate: 93.25%

In [66]:
#查看不同交易类型和状态的组合
transaction_status_summary = pd.crosstab(
    transactions["kind"],
    transactions["status"]
)

transaction_status_summary

status         error  failure  pending  success
kind
authorization      0      102        0     1054
capture            1        0        0     1050
refund             0        7        0     3805
sale               1     1731       18    19790
void               0        0        0        4

In [68]:
# 临时转换日期，只用于检查范围，不修改原表
order_dates = pd.to_datetime(
    orders["created_at"],
    errors="coerce"
)

traffic_dates = pd.to_datetime(
    traffic["date_day"],
    errors="coerce"
)

transaction_dates = pd.to_datetime(
    transactions["created_at"],
    errors="coerce"
)

print(
    "Orders date range:",
    order_dates.min(),
    "to",
    order_dates.max()
)

print(
    "Traffic date range:",
    traffic_dates.min(),
    "to",
    traffic_dates.max()
)

print(
    "Transactions date range:",
    transaction_dates.min(),
    "to",
    transaction_dates.max()
)

Orders date range: 2016-08-21 00:00:00 to 2018-03-22 00:00:00
Traffic date range: 2016-08-17 00:00:00 to 2018-03-18 00:00:00
Transactions date range: 2016-08-21 00:00:00 to 2018-03-21 00:00:00

In [69]:
# 订单金额异常检查
print(
    "Orders with negative total_price:",
    (orders["total_price"] < 0).sum()
)

print(
    "Orders with negative subtotal_price:",
    (orders["subtotal_price"] < 0).sum()
)

print(
    "Orders with negative discounts:",
    (orders["total_discounts"] < 0).sum()
)

print(
    "Orders with total_price equal to 0:",
    (orders["total_price"] == 0).sum()
)

Orders with negative total_price: 0
Orders with negative subtotal_price: 0
Orders with negative discounts: 0
Orders with total_price equal to 0: 678

In [70]:
zero_price_orders = orders[
    orders["total_price"] == 0
]

print(
    zero_price_orders["fulfillment_status"]
    .value_counts(dropna=False)
)

fulfillment_status
fulfilled    638
NaN           37
partial        3
Name: count, dtype: int64

In [71]:
missing_fulfillment_orders = orders[
    orders["fulfillment_status"].isna()
]

print(
    missing_fulfillment_orders["total_price"]
    .value_counts(dropna=False)
    .head()
)

total_price
0.00     37
32.00    29
42.00    17
56.16    11
34.31    10
Name: count, dtype: int64

In [72]:
same_records = (
    (orders["total_price"] == 0)
    ==
    (orders["fulfillment_status"].isna())
).all()

print(
    "Are zero-price orders exactly the same as missing fulfillment orders?",
    same_records
)

Are zero-price orders exactly the same as missing fulfillment orders? False